// Ícones centralizados (react-icons). Trocar o set aqui reflete em todo o app.
export {
  HiOutlineShieldCheck as IconShield,
  HiOutlineShieldExclamation as IconShieldAlert,
  HiOutlineClipboardList as IconPlan,
  HiOutlineSparkles as IconSkills,
  HiOutlineCode as IconCode,
  HiOutlineDocumentSearch as IconScan,
  HiOutlineAdjustments as IconRefactor,
  HiOutlineViewGrid as IconDashboard,
  HiOutlineDocumentText as IconFile,
  HiOutlineLocationMarker as IconLine,
  HiOutlineSun as IconSun,
  HiOutlineMoon as IconMoon,
  HiOutlineLogout as IconLogout,
  HiOutlineChevronRight as IconChevronRight,
  HiOutlineCheck as IconCheck,
  HiOutlineCheckCircle as IconCheckCircle,
  HiOutlineX as IconX,
  HiOutlineXCircle as IconXCircle,
  HiOutlineExclamation as IconWarn,
  HiOutlineExclamationCircle as IconWarnCircle,
  HiOutlineExternalLink as IconExternal,
  HiOutlineDownload as IconDownload,
  HiOutlinePlay as IconPlay,
  HiOutlineArrowLeft as IconArrowLeft,
  HiOutlineRefresh as IconRefresh,
  HiOutlineChip as IconChip,
  HiOutlineCube as IconPackage,
  HiOutlineDatabase as IconRepo,
  HiOutlineLockClosed as IconLock,
  HiOutlineKey as IconKey,
  HiOutlineTerminal as IconTerminal,
  HiOutlineBeaker as IconBeaker,
  HiOutlineDocumentReport as IconReport,
  HiOutlineLightningBolt as IconBolt,
  HiOutlineInformationCircle as IconInfo,
  HiOutlineChevronDown as IconChevronDown,
  HiOutlineQuestionMarkCircle as IconHelp,
} from "react-icons/hi";

export { VscGitPullRequestCreate as IconPullRequest } from "react-icons/vsc";
